FROM debian:bookworm-slim
RUN apt-get update && apt-get install -y tor && rm -rf /var/lib/apt/lists/*
EXPOSE 9050
RUN adduser --disabled-password --uid 1000 --home /data --gecos "" tor
USER tor

ENTRYPOINT ["tor"]
